# Generated by Django 4.2.6 on 2023-10-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            'CREATE TABLE IF NOT EXISTS main_course ('
            'course_id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,'
            'description  VARCHAR(1000) NOT NULL,'
            'access_duration  INTEGER NOT NULL,'
            'net_amount  NUMERIC(6,2) NOT NULL,'
            'vat  NUMERIC(3,2) NOT NULL,'
            'language_cd  VARCHAR(2) NOT NULL'
            ');'

        )
    ]
