# Generated by Django 4.2.7 on 2023-12-05 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_add_delete_procedure'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION calculate_total_price(vId INTEGER)
                RETURNS numeric AS 'SELECT net_amount * (1+vat) FROM main_course WHERE course_id=vId;'
                LANGUAGE SQL
                IMMUTABLE
                RETURNS NULL ON NULL INPUT;
            """
        ),
    ]
