# Generated by Django 4.2.6 on 2023-10-29 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_add_table_course'),
        ('main', '0002_add_user_tables')
    ]

    operations = [
        migrations.RunSQL(
            'CREATE TABLE IF NOT EXISTS main_asset ('
            'asset_id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,'
            'image  BYTEA);'
        )
    ]
