# Generated by Django 4.2.7 on 2023-11-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_exam_exam_question_table'),
    ]

    operations = [
    ]
