# Generated by Django 4.2.7 on 2023-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0009_add_mentor_to_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("asset_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "main_asset",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("certificate_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                ("certificate_pdf_path", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "main_certificate",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=1000)),
                ("access_duration", models.IntegerField()),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("vat", models.DecimalField(decimal_places=2, max_digits=3)),
                ("language_cd", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "main_course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                ("max_score", models.IntegerField()),
                ("passed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "main_exam",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exam_Exam_Question",
            fields=[
                (
                    "exam_exam_question_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "main_exam_exam_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exam_Question",
            fields=[
                (
                    "exam_question_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "main_exam_question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exam_Question_Answer",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=1000)),
                ("correct", models.BooleanField()),
            ],
            options={
                "db_table": "main_exam_question_answer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("lesson_id", models.AutoField(primary_key=True, serialize=False)),
                ("seqence", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "main_lesson",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson_Content",
            fields=[
                (
                    "lesson_content_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("seqence", models.CharField(max_length=1000)),
                ("content_type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "main_lesson_content",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                ("mentor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("email", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
            ],
            options={
                "db_table": "main_mentor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("seqence", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "main_subject",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("address", models.CharField(max_length=100)),
                (
                    "building_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("postal_code", models.CharField(max_length=6)),
                ("city", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "main_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User_Course",
            fields=[
                ("user_course_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "main_user_course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User_Exam",
            fields=[
                ("user_exam_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "main_user_exam",
                "managed": False,
            },
        ),
    ]
